name: student_management
description: ""
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  animations: ^2.0.11
  loading_animation_widget: ^1.2.1
  page_transition: ^2.1.0
  awesome_floating_bottom_navigation: ^0.0.1
  flutter_barcode_scanner: ^2.0.0
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.9
  animated_snack_bar: ^0.4.0
  dart_casing: ^3.0.1
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  qr_flutter: ^4.1.0
  date_time_format: ^2.0.1
  intl: 0.17.0-nullsafety.2
  flutter_local_notifications: ^17.0.0
  firebase_admin: ^0.2.0-dev.7
  email_otp: ^2.0.1
  auth_handler: ^1.0.0
  location: ^5.0.0
  excel: ^4.0.3
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  share_plus: ^8.0.3
  webview_flutter: ^4.7.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/.env
  fonts:
    - family: KaushanScript
      fonts:
        - asset: assets/fonts/KaushanScript-Regular.ttf
